### ISSUE TITLE
Error in _evict()

### ISSUE THREAD

**Issue by oleiba** [feross/bittorrent-dht#117]
Hi, I get this error:
```
/var/app/current/node_modules/bittorrent-dht/client.js:658
  swap(values, b.index, values.length - 1)
                ^
TypeError: Cannot read property 'index' of undefined
    at PeerStore._evict (/var/app/current/node_modules/bittorrent-dht/client.js:658:17)
    at PeerStore.add (/var/app/current/node_modules/bittorrent-dht/client.js:651:36)
    at DHT._addPeer (/var/app/current/node_modules/bittorrent-dht/client.js:420:15)
    at DHT._onannouncepeer (/var/app/current/node_modules/bittorrent-dht/client.js:415:8)
    at DHT._onquery (/var/app/current/node_modules/bittorrent-dht/client.js:369:19)
    at RPC.onquery (/var/app/current/node_modules/bittorrent-dht/client.js:55:10)
    at RPC.emit (events.js:110:17)
    at RPC.onquery (/var/app/current/node_modules/k-rpc/index.js:66:10)
    at RPC.emit (events.js:110:17)
    at Socket.onmessage (/var/app/current/node_modules/k-rpc-socket/index.js:109:12)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```
Use case: this happens *every* 24 hours in my server, when seeding ~2500 torrents.
Most probably related to lru module.

**Comment by mafintosh** [comment]
which version of bt dht are you using?

**Comment by oleiba** [comment]
6.4.0

**Comment by mafintosh** [comment]
could you check which version of lru is installed in node_modules as well?

**Comment by oleiba** [comment]
sure: 2.0.0

**Comment by mafintosh** [comment]
should be fixed in 6.4.1 - could you verify?

it seems greenkeeper bumped lru to 2.0 even though we weren't compatible with that.
i guess we need some more tests for that

**Comment by oleiba** [comment]
Sure, I'll re-deploy with the new version an let you know.
BTW, didn't you mean 6.4.**2** ?

**Comment by mafintosh** [comment]
Sorry yea
