### ISSUE TITLE
Nearly always getting `Error: Socket is already bound`

### ISSUE THREAD

**Issue by matteomonti** [feross/bittorrent-dht#152]
Here is my snippet of code:

```
var DHT = require('bittorrent-dht')
var dht = new DHT();

dht.listen(function () {
  console.log('now listening')
})
```
Nearly whenever I run it (and by nearly I mean that actually one time everything went smoothly and I got a nice `now listening` message) I get

```
Error: Socket is already bound
    at Socket.bind (dgram.js:140:11)
    at RPC.bind (/home/rain/node_modules/k-rpc-socket/index.js:137:15)
    at RPC.bind (/home/rain/node_modules/k-rpc/index.js:104:15)
    at DHT.listen (/home/rain/node_modules/bittorrent-dht/client.js:355:13)
    at DHT.listen (/home/rain/node_modules/bittorrent-dht/client.js:354:47)
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:336:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```
The snippet looks super simple, but maybe I am doing something wrong here? I am confused. I also tried multiple times with multiple ports that I know to be free (I can bind them from anywhere else) but I still got the same error.

**Comment by feross** [comment]
You have to call `listen()` immediately (in the same tick) as when you create the DHT. For some reason, when you run the code you shared in the REPL, that's not happening, and so the DHT has already started listening by the time you call `listen()`. If you run this, it works:

```js
(new (require('bittorrent-dht'))).listen(console.log)
```
