### ISSUE TITLE
Crash on DHT put

### ISSUE THREAD

**Issue by cjb** [feross/bittorrent-dht#66]
(Seen on @substack's dht-store branch, but filing here.)
```
  bittorrent-dht [2f01a3c] put from 98.100.36.218:6881 +1ms

/home/cjb/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:225
    if ((id.length <= bytesDescribedByBitIndex)
           ^
TypeError: Cannot read property 'length' of undefined
    at KBucket.determineBucket (/home/cjb/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:225:12)
    at KBucket.get (/home/cjb/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:258:18)
    at DHT._onPut (/home/cjb/gittorrent/node_modules/bittorrent-dht/client.js:486:27)
    at DHT._onQuery (/home/cjb/gittorrent/node_modules/bittorrent-dht/client.js:1052:30)
    at DHT._onData (/home/cjb/gittorrent/node_modules/bittorrent-dht/client.js:1036:10)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
```
I don't control this node, so have no idea what they were doing :)

**Comment by mafintosh** [comment]
should be fixed in 4.0.1
