### ISSUE TITLE
Bad Argument and Allocation failed

### ISSUE THREAD

**Issue by herlon214** [feross/bittorrent-dht#72]
Hi guys, I have a algorithm that check the peers on a torrent, after sometime this error happen:

```javscript
TypeError: Bad argument
    at new Buffer (buffer.js:194:21)
    at idToBuffer (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:1302:12)
    at DHT._addNode (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:336:12)
    at DHT._onData (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:714:10)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)

buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
TypeError: Bad argument
    at new Buffer (buffer.js:194:21)
    at idToBuffer (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:1302:12)
    at DHT._addNode (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:336:12)
    at DHT._onData (/home/dhseja/torrent_crawl/node_modules/bittorrent-dht/client.js:714:10)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Here is the algorithm:

```javascript
// checker.js
var torrentStream = require('torrent-stream');
var Discovery = require('torrent-discovery');
var DHT = require('bittorrent-dht');
var parseTorrent = require('parse-torrent');
var hat = require('hat');
var Promise = require('bluebird');


module.exports = function(magnet) {
  return new Promise(function(done) {

    var torrent = parseTorrent(magnet);

    var peers = 0;
    var dht = new DHT();
    dht.lookup(torrent.infoHash);
    var discovery = new Discovery({
      peerId: hat(160),
      port: 6000,
      dht: dht
    });

    try {
      discovery.setTorrent(torrent);
      discovery.on('peer', function() {
        peers++;
      });
    }catch(error) {
      console.log(error);
    }




    setTimeout(function() {
      discovery.stop();
      dht.destroy();
      discovery = undefined;
      done(peers);
    }, 60 * 1000);
  });
}


```

An example of use:

```javascript
var checker = require('./checker.js');

checker("magnet:?xt=urn:btih:").then(function(peers) {
 console.log("Peers on this torrent: "+peers);
});
```

Any idea?
Thanks in advance.

**Comment by feross** [comment]
This sounds like the code path that we fixed in the security release (see: https://github.com/feross/bittorrent-dht/issues/87) so I don't think this is an issue anymore.

You should update to the latest version of `bittorrent-dht`.
