### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tsukasagenesis** [feross/bittorrent-dht#76]
hello,

after some time, i got this error :

buffer.js:98
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid typed array length
    at new Uint8Array (native)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at idToBuffer (/root/scripts/tracker/node_modules/bittorrent-dht/client.js:1639:12)
    at DHT._addNode (/root/scripts/tracker/node_modules/bittorrent-dht/client.js:630:12)
    at DHT._onData (/root/scripts/tracker/node_modules/bittorrent-dht/client.js:1025:10)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:481:8)

any idea ?

Best regards,
tsukasagenesis

**Comment by FLYBYME** [comment]
Im getting the same error.

**Comment by feross** [comment]
This sounds like the code path that we fixed in the security release (see: https://github.com/feross/bittorrent-dht/issues/87) so I don't think this is an issue anymore.

You should update to the latest version of `bittorrent-dht`.
